name: Check links
on:
  schedule:
    - cron: "3 15 * * *"
  workflow_dispatch:
jobs:
  linkinator:
    runs-on: ubuntu-26.04
    steps:
      - name: Link checking
        id: link_check
        uses: JustinBeckwith/linkinator-action@12f7a61a56e5e75d659f0dfd6357e2d852ede281 # v2.5.0
        with:
          paths: https://www.digitraffic.fi
          concurrency: 1
          timeout: 10000
          recurse: true
          markdown: true
          retry: true
          # YAML multiline without linebreaks
          linksToSkip: >-  
            https://jsfiddle.net, 
            ^https://www.digitraffic.fi/tiedotteet/(2017|2018|2019|2020|2021|2022)/, 
            ^https://www.digitraffic.fi/en/news/(2017|2018|2019|2020|2021|2022)/, 
            https://maanpuolustus.net, 
            https://digitransit.fi, 
            https://status-test.digitraffic.fi, 
            https://status-test.digitraffic.fi/, 
            https://status.digitraffic.fi/api/, 
            https://rata.digitraffic.fi/vuosisuunnitelmat/, 
            https://www.facebook.com/FintrafficFI, 
            https://www.instagram.com/fintraffic_stories_fi,
            https://liipi.hsl.fi/hubs,
            https://www.gnu.org/software/wget/,
            https://liikenne.palautevayla.fi/feedback
      - name: Notify Slack
        if: failure()
        uses: tmfg/digitraffic-actions@88cc4d1a9c5cb96c037cb0dec41e1c64804b4d0e # slack-notify/v1
        with:
          status: failure
          fields: repo, job
          text: "www.digitraffic.fi link check failed"
          webhook-url: ${{ secrets.SLACK_ALARMS_WEBHOOK_URL }}
