name: Check links
on:
  schedule:
    - cron: "3 15 * * *"
  workflow_dispatch:
jobs:
  linkinator:
    runs-on: ubuntu-latest
    steps:
      - name: Link checking
        id: link_check
        uses: JustinBeckwith/linkinator-action@v1
        with:
          paths: https://www.digitraffic.fi
          concurrency: 5
          timeout: 10000
          recurse: true
          markdown: true
          # YAML multiline without linebreaks
          linksToSkip: >-  
            https://jsfiddle.net, 
            ^https://www.digitraffic.fi/tiedotteet/(2017|2018|2019|2020|2021|2022)/, 
            ^https://www.digitraffic.fi/en/news/(2017|2018|2019|2020|2021|2022)/, 
            https://maanpuolustus.net, 
            https://digitransit.fi, 
            https://status-test.digitraffic.fi, 
            https://status-test.digitraffic.fi/, 
            https://status.digitraffic.fi/api/, 
            https://rata.digitraffic.fi/vuosisuunnitelmat/, 
            https://www.facebook.com/FintrafficFI, 
            https://liipi.hsl.fi/hubs
            https://www.gnu.org/software/wget/
            https://liikenne.palautevayla.fi/feedback
      - name: Notify Slack
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: failure
          fields: repo, job
          text: "www.digitraffic.fi link check failed"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
