name: "Trufflehog secret scanning"

on:
  push:
  pull_request:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Secret scanning
        uses: trufflesecurity/trufflehog@37b77001d0174ebec2fcca2bd83ff83a6d45a3ab # v3.95.3
        with:
          version: 3.94.2@sha256:9587195ca599f525202d19427d4e069a6bbc714e596d693e3041c57a22f5c13b
          base: ""
          head: ${{ github.ref_name }}
          extra_args: --exclude-paths=.github/trufflehog-exclude.txt --results=verified,unknown
